### ISSUE TITLE
Support for Specific Metadata

### ISSUE THREAD

**Issue by zdne** [apiaryio/api-blueprint#38]
Various toolings might have a need for a tooling-specific metadata at different point in blueprint. A solution would be to add a syntax construct that would be expected wherever a Markdown formatted discussion is expected and that would provide (potentially recursive) "key: value" notation. 

E.g.:

```
# API 
API Description

+ Metadata
    + Key: `Value`

# Resource [/resource]
Resource Description 

+ Metadata
    + Key: `Value`
    + Key2:
        + Key3: `Value`

```

Which would be reflected in AST like

```YAML
_version: 1.0
metadata:
name: API
description: "API Description\n\n"
metadata:
    key: Value
resourceGroups:
- name:
  description:
  metadata:
  resources:
  - name: Resource
    description: "Resource Description \n\n"
    metadata:
        key: Value    
        key2:
            key3: Value 
    uriTemplate: /resource
    model:
    parameters:
    headers:
    actions:
```
